/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: 'rgb(var(--color-sage-500))',
          light: 'rgb(var(--color-sage-300))',
          dark: 'rgb(var(--color-sage-700))',
          50: 'rgb(var(--color-sage-50))',
          100: 'rgb(var(--color-sage-100))',
          200: 'rgb(var(--color-sage-200))',
          300: 'rgb(var(--color-sage-300))',
          400: 'rgb(var(--color-sage-400))',
          500: 'rgb(var(--color-sage-500))',
          600: 'rgb(var(--color-sage-600))',
          700: 'rgb(var(--color-sage-700))',
          800: 'rgb(var(--color-sage-800))',
          900: 'rgb(var(--color-sage-900))',
        },
        secondary: {
          DEFAULT: 'rgb(var(--color-tan-500))',
          light: 'rgb(var(--color-tan-300))',
          dark: 'rgb(var(--color-tan-700))',
          50: 'rgb(var(--color-tan-50))',
          100: 'rgb(var(--color-tan-100))',
          200: 'rgb(var(--color-tan-200))',
          300: 'rgb(var(--color-tan-300))',
          400: 'rgb(var(--color-tan-400))',
          500: 'rgb(var(--color-tan-500))',
          600: 'rgb(var(--color-tan-600))',
          700: 'rgb(var(--color-tan-700))',
          800: 'rgb(var(--color-tan-800))',
          900: 'rgb(var(--color-tan-900))',
        },
        accent: {
          DEFAULT: 'rgb(var(--color-gold-500))',
          light: 'rgb(var(--color-gold-300))',
          dark: 'rgb(var(--color-gold-700))',
        },
        sage: {
          DEFAULT: 'rgb(var(--color-sage-500))',
          light: 'rgb(var(--color-sage-300))',
          dark: 'rgb(var(--color-sage-700))',
          50: 'rgb(var(--color-sage-50))',
          100: 'rgb(var(--color-sage-100))',
          200: 'rgb(var(--color-sage-200))',
          300: 'rgb(var(--color-sage-300))',
          400: 'rgb(var(--color-sage-400))',
          500: 'rgb(var(--color-sage-500))',
          600: 'rgb(var(--color-sage-600))',
          700: 'rgb(var(--color-sage-700))',
          800: 'rgb(var(--color-sage-800))',
          900: 'rgb(var(--color-sage-900))',
        },
        tan: {
          DEFAULT: 'rgb(var(--color-tan-500))',
          light: 'rgb(var(--color-tan-300))',
          dark: 'rgb(var(--color-tan-700))',
          50: 'rgb(var(--color-tan-50))',
          100: 'rgb(var(--color-tan-100))',
          200: 'rgb(var(--color-tan-200))',
          300: 'rgb(var(--color-tan-300))',
          400: 'rgb(var(--color-tan-400))',
          500: 'rgb(var(--color-tan-500))',
          600: 'rgb(var(--color-tan-600))',
          700: 'rgb(var(--color-tan-700))',
          800: 'rgb(var(--color-tan-800))',
          900: 'rgb(var(--color-tan-900))',
        },
        gold: {
          DEFAULT: 'rgb(var(--color-gold-500))',
          light: 'rgb(var(--color-gold-300))',
          dark: 'rgb(var(--color-gold-700))',
        },
        cream: 'rgb(var(--color-cream))',
        ink: {
          DEFAULT: 'rgb(var(--color-ink))',
          soft: 'rgb(var(--color-ink-soft))',
          contrast: 'rgb(var(--color-ink-contrast))',
        },
        warm: {
          white: 'rgb(var(--color-cream))',
        },
        neutral: {
          50: 'rgb(var(--color-neutral-50))',
          100: 'rgb(var(--color-neutral-100))',
          200: 'rgb(var(--color-neutral-200))',
          300: 'rgb(var(--color-neutral-300))',
          400: 'rgb(var(--color-neutral-400))',
          500: 'rgb(var(--color-neutral-500))',
          600: 'rgb(var(--color-neutral-600))',
          700: 'rgb(var(--color-neutral-700))',
          800: 'rgb(var(--color-neutral-800))',
          900: 'rgb(var(--color-neutral-900))',
        },
        success: 'rgb(var(--color-success))',
        warning: 'rgb(var(--color-warning))',
        error: 'rgb(var(--color-error))',
        info: 'rgb(var(--color-info))',
        line: 'rgba(var(--color-line-rgb), 0.6)',
        surface: {
          DEFAULT: 'rgb(var(--color-surface))',
          alt: 'rgb(var(--color-surface-alt))',
          contrast: 'rgb(var(--color-surface-contrast))',
        },
      },
      fontFamily: {
        display: ['Cinzel', 'serif'],          // Elegant serif for headings (Style Guide)
        accent: ['Cormorant', 'serif'],        // Italic serif for subheadings (Style Guide)
        body: ['Inter', 'sans-serif'],         // Clean sans-serif for body (Style Guide)
        ui: ['Inter', 'sans-serif'],           // UI elements
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-hero': 'var(--gradient-hero)',
        'gradient-card': 'var(--gradient-card)',
        'gradient-button': 'var(--gradient-button)',
        'gradient-frame': 'var(--gradient-frame)',
        'gradient-divider': 'var(--gradient-divider)',
        'gradient-overlay': 'var(--gradient-overlay)',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'slide-down': 'slideDown 0.3s ease-out',
        'float': 'float 6s ease-in-out infinite',
        'shimmer': 'shimmer 3s ease-in-out infinite',
        'dust-float': 'dustFloat 15s linear infinite',
        'glow': 'glow 2s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
          '100%': { backgroundPosition: '0% 50%' },
        },
        dustFloat: {
          '0%, 100%': { 
            transform: 'translateY(0) translateX(0) rotate(0deg)',
            opacity: '0',
          },
          '10%': { opacity: '0.3' },
          '90%': { opacity: '0.3' },
          '100%': { 
            transform: 'translateY(-100vh) translateX(50px) rotate(360deg)',
            opacity: '0',
          },
        },
        glow: {
          '0%, 100%': { opacity: '0.8' },
          '50%': { opacity: '1' },
        },
      },
      boxShadow: {
        'luxury': '0 20px 40px rgba(196, 165, 123, 0.2)',
        'luxury-hover': '0 25px 50px rgba(196, 165, 123, 0.3)',
        'night-glow': '0 0 30px rgba(80, 200, 120, 0.4)',
      },
    },
  },
  plugins: [
    require('tailwindcss-animate'),
  ],
};