import {
  Users,
  Calendar,
  DollarSign,
  Globe,
  Flame,
  Heart,
  Palette,
  Star,
  Coffee,
  Tent,
  ArrowRight,
  Mountain,
  Award,
  Layers,
  MapPin,
  Eye,
  Wrench,
  GraduationCap,
  Music,
  Clock,
  Gift,
  Truck,
  BarChart3,
  CheckCircle,
  BookOpen,
  Shield,
  Search,
  FileText,
  type LucideIcon,
} from 'lucide-react';

const iconMap: Record<string, LucideIcon> = {
  users: Users,
  calendar: Calendar,
  'dollar-sign': DollarSign,
  globe: Globe,
  flame: Flame,
  heart: Heart,
  palette: Palette,
  star: Star,
  coffee: Coffee,
  tent: Tent,
  'arrow-right': ArrowRight,
  mountain: Mountain,
  award: Award,
  layers: Layers,
  'map-pin': MapPin,
  eye: Eye,
  wrench: Wrench,
  'graduation-cap': GraduationCap,
  music: Music,
  clock: Clock,
  gift: Gift,
  truck: Truck,
  'bar-chart-3': BarChart3,
  'check-circle': CheckCircle,
  'book-open': BookOpen,
  shield: Shield,
  search: Search,
  'file-text': FileText,
};

export function getIcon(iconName: string): LucideIcon {
  return iconMap[iconName.toLowerCase()] || Star;
}
